apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: lamp-dev
  labels:
    app: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c2VjcmV0
  MYSQL_DATABASE: dXN1YXJpb3M=
  MYSQL_USER: Y2hyaXN0aWFu
  MYSQL_PASSWORD: c2VjcmV0 
